"""Apply P1 semantic gloss cleanup.

Per user plan (2026-06-21, "P1 Semantic Gloss Cleanup"):

  Rewrite bad glosses (that pass P0 hygiene but fail validator) so every
  touched row passes ``validate_verdict()``:

  - total words 1-6
  - '|' chunks 1-4 words each (max 2 sides)
  - ';' chunks 1-3 words each (max 2 sides)
  - no headword in chunk
  - no morphological near-self
  - no visible POS labels

  The rewrite is generated by ``src.deck_builder.gloss_p1.fix_one`` —
  a heuristic engine with explicit FIXES overrides for hard cases.

Touches (with explicit old-value guard — key = (word, pos, cefr, old_gloss)):
  - data/audit_full_deck_v2.jsonl
  - data/audit_expanded_needs_gloss_filled.jsonl
  - English Academic Vocabulary.txt  (Definition column)

Backups:
  - Each target gets a .bak_pre_gloss_p1_<timestamp> next to it.

Safety:
  - Default refuses to write unless --apply is given. Use --dry-run to preview.
  - Old-value guard: a row's gloss is only updated if the current gloss_after
    matches the engine's expected input. This prevents accidentally rewriting
    a row that was already fixed by another path.

Out of scope (P2):
  - 5 duplicate (word, pos, cefr) keys
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(r'C:\Users\admin\Downloads\ankideck')
sys.path.insert(0, str(PROJECT_ROOT))

from src.deck_builder.gloss_hygiene import normalize_gloss  # noqa: E402
from src.deck_builder.gloss_llm import validate_verdict  # noqa: E402
from src.deck_builder.gloss_p1 import fix_one, EXPLICIT_FIXES  # noqa: E402

MASTER_AUDIT = PROJECT_ROOT / 'data' / 'audit_full_deck_v2.jsonl'
EXPANDED_FILLED = PROJECT_ROOT / 'data' / 'audit_expanded_needs_gloss_filled.jsonl'
DECK_TXT = PROJECT_ROOT / 'English Academic Vocabulary.txt'


def _ts() -> str:
    return datetime.now().strftime('%Y%m%d_%H%M%S')


def backup(path: Path) -> Path:
    bak = path.with_suffix(path.suffix + f'.bak_pre_gloss_p1_{_ts()}')
    bak.write_bytes(path.read_bytes())
    return bak


# =============================================================================
# Audit JSONL files
# =============================================================================

def chunk_count(g: str) -> int:
    import re
    return len([c for c in re.split(r'\s*[|;]\s*', g.strip()) if c.strip()])


def is_bad(r: dict) -> bool:
    """Check if a row's gloss_after fails validator (post-P0 hygiene)."""
    g = r.get('gloss_after') or ''
    if not (isinstance(g, str) and g.strip()):
        return False
    res = normalize_gloss(g)
    v = validate_verdict(r['word'], res.gloss, res.separator, chunk_count(res.gloss))
    return bool(v)


def apply_audit(path: Path, *, dry_run: bool, fix_map: dict[tuple, str]) -> dict:
    """Apply P1 fixes to an audit JSONL file.

    Uses a pre-computed fix_map (key → new_norm). For each row:
      - if currently passes validator: skip (don't touch clean rows)
      - if currently fails validator AND key in fix_map: update
      - if currently fails validator AND key not in fix_map: leave as-is
        (engine couldn't generate a fix — counts as 'no_fix_available')

    Returns stats dict.
    """
    stats = Counter(
        total=0,
        bad_rows=0,
        fixed=0,
        no_fix_available=0,
        old_value_mismatch=0,
        clean_skipped=0,
    )

    rows_in = []
    with path.open(encoding='utf-8') as fp:
        for line in fp:
            if not line.strip():
                continue
            rows_in.append(json.loads(line))

    new_rows = []
    for r in rows_in:
        stats['total'] += 1
        key_override = (r['word'], r['pos'], r['cefr'])
        if not is_bad(r) and key_override not in EXPLICIT_FIXES:
            stats['clean_skipped'] += 1
            new_rows.append(r)
            continue
        stats['bad_rows'] += 1

        old_gloss = r['gloss_after']
        old_norm = normalize_gloss(old_gloss).gloss
        key = (r['word'], r['pos'], r['cefr'], old_norm)
        if key not in fix_map:
            stats['no_fix_available'] += 1
            new_rows.append(r)
            continue

        new_gloss = fix_map[key]

        if old_norm == new_gloss:
            stats['old_value_mismatch'] += 1
            new_rows.append(r)
            continue

        r['gloss_after'] = new_gloss
        # Recompute separator + word count via normalize.
        res = normalize_gloss(new_gloss)
        r['separator'] = res.separator
        r['gloss_word_count'] = res.gloss_word_count
        # Mark fix_status so downstream knows it came from P1 path.
        r['fix_status'] = 'p1_rewritten'
        stats['fixed'] += 1
        new_rows.append(r)

    if not dry_run and stats['fixed']:
        tmp = path.with_suffix(path.suffix + '.tmp_p1')
        with tmp.open('w', encoding='utf-8', newline='') as fp:
            for r in new_rows:
                fp.write(json.dumps(r, ensure_ascii=False))
                fp.write('\n')
        tmp.replace(path)

    return dict(stats)


# =============================================================================
# TXT deck file
# =============================================================================

def apply_txt(path: Path, *, dry_run: bool, fix_map: dict[tuple, str]) -> dict:
    """Apply P1 fixes to the Definition column (index 6) of the TXT deck file.

    Uses a pre-computed fix_map (key → new_norm). Joins via
    (word, pos, cefr, old_gloss_after) key.

    Only updates a def cell if:
      - key is in fix_map
    """
    stats = Counter(
        total=0,
        rows_with_def=0,
        updated=0,
        no_match=0,
        mismatch=0,
    )

    raw_lines = path.read_text(encoding='utf-8').splitlines(keepends=False)
    header_lines = []
    body_start = 0
    for i, line in enumerate(raw_lines):
        if line.startswith('#'):
            header_lines.append(line)
        else:
            body_start = i
            break
    else:
        body_start = len(raw_lines)

    body_lines = raw_lines[body_start:]
    new_body = []
    for line in body_lines:
        stats['total'] += 1
        if not line.strip():
            new_body.append(line)
            continue
        fields = line.split('\t')
        if len(fields) <= 6:
            new_body.append(line)
            continue
        stats['rows_with_def'] += 1

        word = fields[3]
        pos = fields[4]
        cefr = fields[14] if len(fields) > 14 else ''
        current_def = normalize_gloss(fields[6]).gloss
        key = (word, pos, cefr, current_def)

        new_gloss = fix_map.get(key)
        if new_gloss is None:
            stats['no_match'] += 1
            new_body.append(line)
            continue

        fields[6] = new_gloss
        new_line = '\t'.join(fields)
        new_body.append(new_line)
        stats['updated'] += 1

    if not dry_run and stats['updated']:
        all_lines = header_lines + new_body
        text_out = '\n'.join(all_lines) + '\n'
        tmp = path.with_suffix(path.suffix + '.tmp_p1')
        tmp.write_text(text_out, encoding='utf-8')
        tmp.replace(path)

    return dict(stats)


def compute_fix_map(master_path: Path) -> dict[tuple, str]:
    """Compute the (word, pos, cefr, old_gloss_after) → new_norm map from the master audit.

    Only considers rows whose CURRENT gloss fails the validator — clean rows
    are NOT in the map (they're already valid; the engine shouldn't pretend
    they need fixing).

    If multiple rows share the same key, keep the LAST one in file order
    (master is sorted deterministically by (word, source_files[0]) per the
    rebuild contract).
    """
    fix_map: dict[tuple, str] = {}
    with master_path.open(encoding='utf-8') as fp:
        for line in fp:
            if not line.strip():
                continue
            r = json.loads(line)
            old = r.get('gloss_after') or ''
            if not old.strip():
                continue
            # Skip rows that already pass validator — we don't want to "fix"
            # clean glosses unless explicitly requested in EXPLICIT_FIXES.
            key_override = (r['word'], r['pos'], r['cefr'])
            if not is_bad(r) and key_override not in EXPLICIT_FIXES:
                continue
            new = fix_one(
                r['word'], r['pos'], r['cefr'],
                old, r.get('def_before', ''),
            )
            if new is None:
                continue
            new_norm = normalize_gloss(new).gloss
            old_norm = normalize_gloss(old).gloss
            if new_norm == old_norm:
                continue
            key = (r['word'], r['pos'], r['cefr'], old_norm)
            fix_map[key] = new_norm
    return fix_map


# =============================================================================
# Main
# =============================================================================

def main() -> int:
    ap = argparse.ArgumentParser(description='Apply P1 semantic gloss cleanup.')
    ap.add_argument('--dry-run', action='store_true',
                    help='Preview without writing.')
    ap.add_argument('--targets', nargs='*',
                    choices=['master', 'filled', 'txt'],
                    help='Limit which files to touch (default: all).')
    args = ap.parse_args()

    targets = args.targets or ['master', 'filled', 'txt']

    print('=' * 72)
    print(f'P1 Semantic Gloss Cleanup  (dry-run={args.dry_run})')
    print(f'Timestamp: {_ts()}')
    print('=' * 72)

    # Step 0: compute the fix map from the master audit ONCE.
    # This ensures master/filled/TXT all see the same set of fixes.
    print(f'\n[0/3] Computing fix map from {MASTER_AUDIT.name}...')
    fix_map = compute_fix_map(MASTER_AUDIT)
    print(f'  unique (word, pos, cefr) keys with fixes: {len(fix_map)}')

    # --- Audit: master ---
    if 'master' in targets:
        print(f'\n[1/3] {MASTER_AUDIT.name}')
        if not args.dry_run:
            bak = backup(MASTER_AUDIT)
            print(f'  backup: {bak.name}')
        s = apply_audit(MASTER_AUDIT, dry_run=args.dry_run, fix_map=fix_map)
        print(f"  rows: {s['total']}  bad: {s['bad_rows']}  fixed: {s['fixed']}  "
              f"no_fix: {s['no_fix_available']}  old_mismatch: {s['old_value_mismatch']}")

    # --- Audit: filled ---
    if 'filled' in targets:
        print(f'\n[2/3] {EXPANDED_FILLED.name}')
        if not args.dry_run:
            bak = backup(EXPANDED_FILLED)
            print(f'  backup: {bak.name}')
        s = apply_audit(EXPANDED_FILLED, dry_run=args.dry_run, fix_map=fix_map)
        print(f"  rows: {s['total']}  bad: {s['bad_rows']}  fixed: {s['fixed']}  "
              f"no_fix: {s['no_fix_available']}  old_mismatch: {s['old_value_mismatch']}")

    # --- TXT ---
    if 'txt' in targets:
        print(f'\n[3/3] {DECK_TXT.name}')
        if not args.dry_run:
            bak = backup(DECK_TXT)
            print(f'  backup: {bak.name}')
        s = apply_txt(DECK_TXT, dry_run=args.dry_run, fix_map=fix_map)
        print(f"  rows: {s['total']}  with_def: {s['rows_with_def']}  "
              f"updated: {s['updated']}  no_match: {s['no_match']}")

    print('\nDone.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
